version: '3'
services:
    app:
        build: ./app
        command: npm run dev
        ports:
          - 3000:3000
        volumes:
          - ./app:/usr/src/app
          - /usr/src/app/node_modules
        links:
          - mongo
    mongo:
        build: ./mongo
        volumes:
          - ./mongo/data/db:/data/db
        ports:
          - 27017:27017